name: Build_gl_be3600

on:
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: '10 19 * * 5'

jobs:
  build:
    name: Build ${{ matrix.model }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        model: ["gl_be3600"]
        include:
          - model: "gl_be3600"

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Free disk space
        uses: xiangfeidexiaohuo/actions@2204
        with:
          build-mount-path: /home/runner/work/isos-build/isos-build

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo -E apt-get update -y
          sudo -E apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev libfuse-dev python3-setuptools g++ file clang nano genisoimage python2
          pip install aligo
          sudo -E apt-get clean
          git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
          df -h

      - name: Checkout Main repo
        uses: actions/checkout@main
        with:
          repository: istoreos/be3600_istoreOS_priv
          ref: istore
          token: ${{ secrets.AC_TOKEN }}
          path: openwrt-${{ matrix.model }}

      - name: Start build
        working-directory: ./openwrt-${{ matrix.model }}
        run: |
          ./scripts/gen_config.py target_qsdk12_5_ipq53xx_gl-be3600

      - name: Download package
        working-directory: ./openwrt-${{ matrix.model }}
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Build firmware
        working-directory: ./openwrt-${{ matrix.model }}
        run: 
          date '+%Y%m%d%H' > version
          make -j$(nproc) V=s || make -j1 V=s

      - name: Prepare artifacts
        id: prepare_artifacts
        run: |
          mkdir -p artifacts/${{ matrix.model }}
          cp -a openwrt-${{ matrix.model }}/bin/targets/ipq53xx/generic/istoreos-ipq53xx-generic-gl-be3600-squashfs-factory.bin artifacts/${{ matrix.model }}/istoreos-gl-be3600-factory-$(date '+%Y%m%d%H').bin
          cp -a openwrt-${{ matrix.model }}/bin/targets/ipq53xx/generic/istoreos-ipq53xx-generic-gl-be3600-squashfs-sysupgrade.tar artifacts/${{ matrix.model }}/istoreos-glbe3600-sysupgrade-$(date '+%Y%m%d%H').tar

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.model }}-firmware
          path: artifacts/${{ matrix.model }}/*.*

